= (Worksheet as text) => let
    Source = Excel.Workbook(File.Contents("C:\Users\mghaf\OneDrive\Desktop\Data analysis\HR_Data_Analysis\Data\Attendance_Sheet.xlsx"), null, true),
        #"Filtered Rows" = Table.SelectRows(Source, each [Name] = Worksheet),
        #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Data"}),
        Data = #"Removed Other Columns"{0}[Data],
        #"Changed Type" = Table.TransformColumnTypes(Data,{{"Column1", type text}, {"Column2", type text}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}}),
        #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
        #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"AtliQ", type text}, {"Column2", type text}, {"4/1/2022", type any}, {"4/2/2022", type any}, {"4/3/2022", type any}, {"4/4/2022", type any}, {"4/5/2022", type any}, {"4/6/2022", type any}, {"4/7/2022", type any}, {"4/8/2022", type any}, {"4/9/2022", type any}, {"4/10/2022", type any}, {"4/11/2022", type any}, {"4/12/2022", type any}, {"4/13/2022", type any}, {"4/14/2022", type any}, {"4/15/2022", type any}, {"4/16/2022", type any}, {"4/17/2022", type any}, {"4/18/2022", type any}, {"4/19/2022", type any}, {"4/20/2022", type any}, {"4/21/2022", type any}, {"4/22/2022", type any}, {"4/23/2022", type any}, {"4/24/2022", type any}, {"4/25/2022", type any}, {"4/26/2022", type any}, {"4/27/2022", type any}, {"4/28/2022", type any}, {"4/29/2022", type any}, {"4/30/2022", type any}, {"5/1/2022", Int64.Type}, {"Total Present Days", type any}, {"Present", type any}, {"Work from home ", type any}, {"Paid Leave ", type any}, {"Sick Leave ", type any}, {"Birthday Leave ", type any}, {"Floting festival leave ", type any}, {"Bereavement Leave", type any}, {"Leave without pay", type any}, {"Weekly Off", type any}, {"Holidays Off", type any}, {"Menstrual Leave", type any}}),
        #"Removed Top Rows" = Table.Skip(#"Changed Type1",1),
        #"Renamed Columns" = Table.RenameColumns(#"Removed Top Rows",{{"AtliQ", "Employee_code"}, {"Column2", "Name"}}),
        #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Employee_code", "Name"}, "Attribute", "Value"),
        #"Changed Type2" = Table.TransformColumnTypes(#"Unpivoted Other Columns",{{"Value", type text}}),
        #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Attribute", "Date"}}),
        #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Date", type date}}),
        #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type3", {"Date"})
in
    #"Removed Errors"